language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  # clippy doesn't work on nightly
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ] ; then rustup component add clippy; fi
  - rustup component add rustfmt
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo fmt -- --check
  # clippy doesn't work on nightly
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ] cargo clippy -- -D warnings; fi
  - cargo build --release
  - cargo test
  # benches only work on nightly
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ] ; then cargo bench --verbose; fi
