language: rust
rust:
  - stable
  - beta
before_script:
  - rustup component add clippy
  - rustup component add rustfmt
script:
  - cargo fmt -- --check
  - cargo clippy
  - cargo build --release
  - cargo test
  - cargo bench
