[package]
authors = ["Maximilian Krüger <kruemaxi@gmail.com>"]
name = "apodize"
version = "0.1.1"
description = "iterators that yield generalized cosine, hanning, hamming, blackman and nuttall windows"
documentation = "https://snd.github.io/apodize/apodize/index.html"
homepage = "https://github.com/snd/apodize"
repository = "https://github.com/snd/apodize.git"
readme = "README.md"
keywords = ["iterator", "window", "hanning", "hamming", "blackman"]
license = "MIT OR Apache-2.0"

[dependencies]
num = "0.1.29"
nalgebra = "0.4.0"
